import { Project, Task } from './types';

export const MOCK_TASKS: Task[] = [
  {
    id: 1,
    title: "Roof Structural Analysis",
    description: "Conduct structural analysis of Building A roof to determine load capacity for solar panels.",
    status: 'completed',
    team: 'architecture',
    due_date: new Date("2024-02-15"),
    tentative: false,
    assigned_by: "John Green",
    assignees: ["John Green", "Jane Doe"],
    priority: 'extreme',
    lifecycle_project_id: 1,
    created_at: new Date("2024-01-01"),
    updated_at: new Date("2024-02-16"),
  },
  {
    id: 2,
    title: "Energy Usage Study",
    description: "Analyze current energy usage patterns to establish baseline metrics.",
    status: 'in_progress',
    team: 'technology',
    due_date: new Date("2024-03-20"),
    tentative: false,
    assigned_by: "John Green",
    assignees: ["Emily Park"],
    priority: 'high',
    lifecycle_project_id: 1,
    created_at: new Date("2024-01-15"),
    updated_at: new Date("2024-03-01"),
  },
  {
    id: 3,
    title: "Community Outreach Plan",
    description: "Develop strategy to inform campus about solar initiative benefits.",
    status: 'pending_approval',
    team: 'public_relations',
    due_date: new Date("2024-04-10"),
    tentative: true,
    assigned_by: "John Green",
    assignees: ["Sophie Martinez"],
    priority: 'medium',
    lifecycle_project_id: 1,
    created_at: new Date("2024-02-01"),
    updated_at: new Date("2024-02-20"),
  },
  {
    id: 4,
    title: "ROI Analysis",
    description: "Calculate projected return on investment over 25-year period.",
    status: 'not_started',
    team: 'finance',
    due_date: new Date("2024-05-01"),
    tentative: false,
    assigned_by: "John Green",
    assignees: ["Rachel Green"],
    priority: 'low',
    lifecycle_project_id: 1,
    created_at: new Date("2024-02-15"),
    updated_at: new Date("2024-02-15"),
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 1,
    project_id: 1,
    title: "Campus Solar Initiative",
    completed: false,
    progress_percent: 25,
    image: undefined,
    tasks: MOCK_TASKS.filter(t => t.lifecycle_project_id === 1),
  },
  {
    id: 2,
    project_id: 1,
    title: "Green Roof Retrofit",
    completed: false,
    progress_percent: 75,
    image: undefined,
    tasks: [],
  },
  {
    id: 3,
    project_id: 1,
    title: "Building Energy Optimization",
    completed: true,
    progress_percent: 100,
    image: undefined,
    tasks: [],
  },
];

export function getProjectById(id: number): Project | undefined {
  return MOCK_PROJECTS.find(p => p.id === id);
}
