-- Content-addressed chat attachment store.
-- Each unique (uid, content_hash) pair is stored once. Subsequent turns
-- reference by hash instead of re-sending the full extracted text, so a
-- 5-turn conversation with one PDF ships the content only on turn 1.
CREATE TABLE public.client_chat_attachments (
  id           bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid          uuid        NOT NULL DEFAULT auth.uid()
                             REFERENCES auth.users(id) ON DELETE CASCADE,
  content_hash text        NOT NULL,   -- lowercase hex SHA-256 of content
  filename     text        NOT NULL,
  file_type    text        NOT NULL DEFAULT 'txt',
  content      text        NOT NULL,
  byte_len     int         NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (uid, content_hash)
);

ALTER TABLE public.client_chat_attachments ENABLE ROW LEVEL SECURITY;

-- Owners can read their own stored attachments (route resolver uses this).
CREATE POLICY "own attachments select"
  ON public.client_chat_attachments
  FOR SELECT TO authenticated
  USING (uid = auth.uid());

-- Owners can insert their own rows; content-addressed so no UPDATE policy needed.
CREATE POLICY "own attachments insert"
  ON public.client_chat_attachments
  FOR INSERT TO authenticated
  WITH CHECK (uid = auth.uid());
