-- Server-recorded model usage for the private staff statistics dashboard.
-- Browser roles have no access; the Next.js server action reads this table via
-- the service-role client after independently verifying staff authorization.

CREATE TABLE public.ai_usage_events (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid                uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  project_id         bigint REFERENCES public.projects(id) ON DELETE SET NULL,
  model              text NOT NULL,
  model_preference   text NOT NULL CHECK (model_preference IN ('fast', 'thinking')),
  reasoning_effort   text,
  prompt_tokens      bigint NOT NULL DEFAULT 0 CHECK (prompt_tokens >= 0),
  completion_tokens  bigint NOT NULL DEFAULT 0 CHECK (completion_tokens >= 0),
  reasoning_tokens   bigint NOT NULL DEFAULT 0 CHECK (reasoning_tokens >= 0),
  total_tokens       bigint NOT NULL DEFAULT 0 CHECK (total_tokens >= 0),
  estimated_cost_usd numeric(14,8) NOT NULL DEFAULT 0 CHECK (estimated_cost_usd >= 0),
  created_at         timestamptz NOT NULL DEFAULT now(),
  metadata           jsonb NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX ai_usage_events_uid_created_idx
  ON public.ai_usage_events (uid, created_at DESC);
CREATE INDEX ai_usage_events_created_idx
  ON public.ai_usage_events (created_at DESC);

ALTER TABLE public.ai_usage_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.ai_usage_events FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.ai_usage_events_id_seq FROM anon, authenticated;
