-- Separate a person's SBI membership profile from their portal login.  A
-- Discord-verified member can exist before they have a Supabase Auth account.

ALTER TABLE public.profiles
  ALTER COLUMN uid DROP NOT NULL,
  ADD COLUMN contact_email text;

ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_uidless_profiles_are_members
  CHECK (uid IS NOT NULL OR role = 'member');

CREATE INDEX idx_profiles_contact_email
  ON public.profiles (lower(contact_email))
  WHERE contact_email IS NOT NULL;
CREATE UNIQUE INDEX profiles_discord_id_unique
  ON public.profiles (discord_id)
  WHERE discord_id IS NOT NULL;

ALTER TABLE public.projects
  ADD COLUMN is_default boolean NOT NULL DEFAULT false;

CREATE UNIQUE INDEX projects_one_default
  ON public.projects ((is_default))
  WHERE is_default;

-- New members receive the default project exactly once.  Clients are excluded
-- and directors keep the existing all-project trigger behavior.
CREATE OR REPLACE FUNCTION public.auto_link_member_to_default_project()
  RETURNS trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'pg_catalog', 'pg_temp'
AS $$
BEGIN
  IF NEW.role = 'member' THEN
    INSERT INTO public.project_members (project_id, profile_id, role)
    SELECT project.id, NEW.id, 'member'::extensions.project_role
    FROM public.projects AS project
    WHERE project.is_default
      AND NOT EXISTS (
        SELECT 1
        FROM public.project_members AS membership
        WHERE membership.profile_id = NEW.id
      )
    ON CONFLICT (project_id, profile_id) DO NOTHING;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_auto_link_member_to_default_project
  AFTER INSERT ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.auto_link_member_to_default_project();

-- This is deliberately an RPC rather than two client-visible UPDATEs: at no
-- point can concurrent requests observe two defaults.  Changing a default only
-- adds currently-unassigned members; it never moves existing memberships.
CREATE OR REPLACE FUNCTION public.set_default_project(_project_id bigint)
  RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'pg_catalog', 'pg_temp'
AS $$
BEGIN
  IF NOT public.is_director(auth.uid()) THEN
    RAISE EXCEPTION 'Director role required' USING ERRCODE = '42501';
  END IF;

  PERFORM 1 FROM public.projects WHERE id = _project_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Project not found' USING ERRCODE = 'P0002';
  END IF;

  UPDATE public.projects SET is_default = false WHERE is_default;
  UPDATE public.projects SET is_default = true WHERE id = _project_id;

  INSERT INTO public.project_members (project_id, profile_id, role)
  SELECT _project_id, profile.id, 'member'::extensions.project_role
  FROM public.profiles AS profile
  WHERE profile.role = 'member'
    AND NOT EXISTS (
      SELECT 1 FROM public.project_members AS membership
      WHERE membership.profile_id = profile.id
    )
  ON CONFLICT (project_id, profile_id) DO NOTHING;
END;
$$;

REVOKE ALL ON FUNCTION public.set_default_project(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.set_default_project(bigint) TO authenticated;

-- Recovery data is deliberately invisible to browser roles.  The import tool
-- uses the service key and stores only the approved core-identity snapshot.
CREATE TABLE public.member_recovery_batches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label text NOT NULL,
  created_by uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  applied_at timestamptz,
  resolution jsonb NOT NULL DEFAULT '[]'::jsonb,
  notes text
);

CREATE TABLE public.member_recovery_profile_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id bigint NOT NULL REFERENCES public.member_recovery_batches(id) ON DELETE CASCADE,
  profile_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  before_identity jsonb,
  after_identity jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.member_recovery_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.member_recovery_profile_snapshots ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.member_recovery_batches, public.member_recovery_profile_snapshots FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.member_recovery_batches_id_seq, public.member_recovery_profile_snapshots_id_seq FROM anon, authenticated;
