-- Folder-level permissions for the project file repository.
--
-- Defaults:
--   Shared / Deliverables: project members can read; directors manage;
--                          clients can read because these are client-visible.
--   Member Inbox:         members can read and upload; only directors manage.
--
-- Paths without a metadata row remain readable by project clients for legacy
-- compatibility; directors can later add an explicit `restricted` row when a
-- folder must be staff-only.

DO $$
BEGIN
  CREATE TYPE extensions.file_folder_access AS ENUM (
    'shared',
    'member_inbox',
    'restricted'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END;
$$;

CREATE TABLE IF NOT EXISTS public.project_file_folders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  path text NOT NULL,
  access_mode extensions.file_folder_access NOT NULL DEFAULT 'shared',
  client_visible boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT project_file_folders_path_check CHECK (
    path = btrim(path)
    AND path NOT LIKE '/%'
    AND path NOT LIKE '%/'
    AND path NOT LIKE '%//%'
    AND path <> ''
  ),
  CONSTRAINT project_file_folders_project_path_key UNIQUE (project_id, path)
);

CREATE INDEX IF NOT EXISTS project_file_folders_project_idx
  ON public.project_file_folders (project_id, path);

ALTER TABLE public.project_file_folders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Project members can view file folder settings"
  ON public.project_file_folders;
CREATE POLICY "Project members can view file folder settings"
  ON public.project_file_folders
  FOR SELECT TO authenticated
  USING (public.is_project_member(project_id));

DROP POLICY IF EXISTS "Directors can manage file folder settings"
  ON public.project_file_folders;
CREATE POLICY "Directors can manage file folder settings"
  ON public.project_file_folders
  FOR ALL TO authenticated
  USING (public.is_director(auth.uid()))
  WITH CHECK (public.is_director(auth.uid()));

GRANT SELECT ON public.project_file_folders TO authenticated;
GRANT INSERT, UPDATE, DELETE ON public.project_file_folders TO authenticated;

CREATE OR REPLACE FUNCTION public.seed_project_file_folders()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'pg_catalog', 'public', 'pg_temp'
AS $$
BEGIN
  INSERT INTO public.project_file_folders
    (project_id, path, access_mode, client_visible)
  VALUES
    (NEW.id, 'Shared', 'shared'::extensions.file_folder_access, true),
    (NEW.id, 'Deliverables', 'shared'::extensions.file_folder_access, true),
    (NEW.id, 'Member Inbox', 'member_inbox'::extensions.file_folder_access, false)
  ON CONFLICT (project_id, path) DO NOTHING;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_seed_project_file_folders ON public.projects;
CREATE TRIGGER trg_seed_project_file_folders
  AFTER INSERT ON public.projects
  FOR EACH ROW EXECUTE FUNCTION public.seed_project_file_folders();

REVOKE EXECUTE ON FUNCTION public.seed_project_file_folders() FROM PUBLIC, anon, authenticated;

-- Defaults for every current and future project. Existing folders are
-- backfilled below so a migration does not silently remove client visibility.
INSERT INTO public.project_file_folders
  (project_id, path, access_mode, client_visible)
SELECT p.id, defaults.path, defaults.access_mode, defaults.client_visible
FROM public.projects AS p
CROSS JOIN (
  VALUES
    ('Shared', 'shared'::extensions.file_folder_access, true),
    ('Deliverables', 'shared'::extensions.file_folder_access, true),
    ('Member Inbox', 'member_inbox'::extensions.file_folder_access, false)
) AS defaults(path, access_mode, client_visible)
ON CONFLICT (project_id, path) DO NOTHING;

-- Preserve access to existing top-level folders such as Media. The row is
  -- explicit and client-visible. Unknown paths retain the legacy client read
  -- behavior until a director configures them as restricted.
INSERT INTO public.project_file_folders
  (project_id, path, access_mode, client_visible)
SELECT DISTINCT
  split_part(objects.name, '/', 1)::bigint,
  split_part(objects.name, '/', 2),
  'shared'::extensions.file_folder_access,
  true
FROM storage.objects AS objects
JOIN public.projects AS p
  ON p.id::text = split_part(objects.name, '/', 1)
WHERE objects.bucket_id = 'Files'
  AND split_part(objects.name, '/', 1) ~ '^[0-9]+$'
  AND split_part(objects.name, '/', 2) <> ''
ON CONFLICT (project_id, path) DO NOTHING;

CREATE OR REPLACE FUNCTION public.storage_path_project_id(object_name text)
RETURNS bigint
LANGUAGE plpgsql
IMMUTABLE
SECURITY DEFINER
SET search_path TO 'pg_catalog', 'public', 'pg_temp'
AS $$
BEGIN
  RETURN split_part(object_name, '/', 1)::bigint;
EXCEPTION
  WHEN invalid_text_representation THEN
    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION public.storage_file_folder_access(
  object_name text
)
RETURNS TABLE (
  project_id bigint,
  access_mode text,
  client_visible boolean
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO 'pg_catalog', 'public', 'pg_temp'
AS $$
DECLARE
  relative_path text;
BEGIN
  project_id := public.storage_path_project_id(object_name);
  IF project_id IS NULL THEN
    RETURN;
  END IF;

  relative_path := regexp_replace(object_name, '^[^/]+/?', '');

  SELECT folders.access_mode::text, folders.client_visible
  INTO access_mode, client_visible
  FROM public.project_file_folders AS folders
  WHERE folders.project_id = storage_file_folder_access.project_id
    AND (
      relative_path = folders.path
      OR relative_path LIKE folders.path || '/%'
    )
  ORDER BY length(folders.path) DESC
  LIMIT 1;

  IF NOT FOUND THEN
    access_mode := 'shared';
    client_visible := true;
  END IF;

  RETURN NEXT;
END;
$$;

CREATE OR REPLACE FUNCTION public.storage_file_can_read(
  check_uid uuid,
  object_name text
)
RETURNS boolean
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path TO 'pg_catalog', 'public', 'pg_temp'
AS $$
DECLARE
  folder record;
  profile_role text;
BEGIN
  IF check_uid IS NULL THEN
    RETURN false;
  END IF;

  SELECT access_mode, client_visible, project_id
  INTO folder
  FROM public.storage_file_folder_access(object_name);
  IF folder.project_id IS NULL OR NOT public.storage_path_project_member(check_uid, object_name) THEN
    RETURN false;
  END IF;
  IF public.is_director(check_uid) THEN
    RETURN true;
  END IF;

  SELECT role::text INTO profile_role
  FROM public.profiles
  WHERE uid = check_uid;

  IF profile_role = 'client' THEN
    RETURN folder.client_visible AND folder.access_mode <> 'restricted';
  END IF;

  RETURN profile_role = 'member'
    AND folder.access_mode IN ('shared', 'member_inbox');
END;
$$;

CREATE OR REPLACE FUNCTION public.storage_file_can_insert(
  check_uid uuid,
  object_name text
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO 'pg_catalog', 'public', 'pg_temp'
AS $$
  SELECT public.is_director(check_uid)
    AND public.storage_path_project_member(check_uid, object_name)
  OR (
    EXISTS (
      SELECT 1
      FROM public.profiles AS profile
      WHERE profile.uid = check_uid AND profile.role = 'member'
    )
    AND public.storage_path_project_member(check_uid, object_name)
    AND EXISTS (
      SELECT 1
      FROM public.storage_file_folder_access(object_name) AS folder
      WHERE folder.access_mode = 'member_inbox'
    )
  );
$$;

CREATE OR REPLACE FUNCTION public.storage_file_can_manage(
  check_uid uuid,
  object_name text
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO 'pg_catalog', 'public', 'pg_temp'
AS $$
  SELECT public.is_director(check_uid)
    AND public.storage_path_project_member(check_uid, object_name);
$$;

REVOKE EXECUTE ON FUNCTION public.storage_path_project_id(text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.storage_file_folder_access(text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.storage_file_can_read(uuid, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.storage_file_can_insert(uuid, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.storage_file_can_manage(uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.storage_path_project_id(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.storage_file_folder_access(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.storage_file_can_read(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.storage_file_can_insert(uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.storage_file_can_manage(uuid, text) TO authenticated;

DROP POLICY IF EXISTS "Allow users to access and upload to buckets 14exqv_0"
  ON storage.objects;
CREATE POLICY "Allow users to read project Files"
  ON storage.objects
  FOR SELECT TO authenticated
  USING (bucket_id = 'Files'::text AND public.storage_file_can_read(auth.uid(), name));

DROP POLICY IF EXISTS "Directors can upload Files" ON storage.objects;
CREATE POLICY "Project members can upload Files"
  ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'Files'::text AND public.storage_file_can_insert(auth.uid(), name));

DROP POLICY IF EXISTS "Directors can update Files" ON storage.objects;
CREATE POLICY "Directors can update Files"
  ON storage.objects
  FOR UPDATE TO authenticated
  USING (bucket_id = 'Files'::text AND public.storage_file_can_manage(auth.uid(), name))
  WITH CHECK (bucket_id = 'Files'::text AND public.storage_file_can_manage(auth.uid(), name));

DROP POLICY IF EXISTS "Directors can delete Files" ON storage.objects;
CREATE POLICY "Directors can delete Files"
  ON storage.objects
  FOR DELETE TO authenticated
  USING (bucket_id = 'Files'::text AND public.storage_file_can_manage(auth.uid(), name));
