-- =====================================================================
-- BASELINE SCHEMA SNAPSHOT
-- =====================================================================
-- Reconstructed from the live `sbi` Supabase project (ref zxqwjnxrkzvygwdltuwi)
-- via read-only introspection. The live database was built by ~33 migrations
-- that were never checked into this repo; only the finance tables + 2 ALTERs
-- existed in VCS. This file captures everything that those finance migrations
-- depend on, so a clean `supabase db reset` applies in this order:
--
--   20260101000000_baseline_schema.sql        <- THIS FILE
--   20260526000000_create_finance_tables.sql  <- project_budgets/categories/
--                                                 transactions + set_updated_at()
--                                                 + is_project_director()
--   20260526000100_add_transaction_title.sql  <- ALTER budget_transactions
--   20260528052326_add_blocked_task_status.sql<- ALTER TYPE task_status ADD 'blocked'
--
-- DELIBERATELY OMITTED (owned by later migrations, so they apply cleanly on top):
--   * Tables  project_budgets, budget_categories, budget_transactions
--   * Function public.set_updated_at()        (CREATE OR REPLACE in finance mig)
--   * Function public.is_project_director()   (CREATE OR REPLACE in finance mig)
--   * Enum label task_status.'blocked'        (added by add_blocked_task_status)
--   * Column budget_transactions.title        (added by add_transaction_title)
--
-- KNOWN-STALE OBJECTS IN LIVE DB, INTENTIONALLY NOT REPRODUCED (see report):
--   * Function public.hybrid_search()         (references dropped table
--                                              client_documents — would not even
--                                              create cleanly)
--   * storage.objects policies for bucket 'request-attachments' (bucket does not
--                                              exist; orphaned policies)
--
-- NOTE ON ENUM SCHEMA: the user-defined enums live in the `extensions` schema in
-- the live DB (not `public`). This is unusual but reproduced faithfully so that
-- column types and the existing finance/ALTER migrations resolve identically.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 0. Extensions & schemas
-- ---------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "uuid-ossp"  WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS pgcrypto     WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS vector        WITH SCHEMA public;

CREATE SCHEMA IF NOT EXISTS private;

-- ---------------------------------------------------------------------
-- 1. Enums (in `extensions` schema, matching live DB)
-- ---------------------------------------------------------------------
DO $$ BEGIN
  CREATE TYPE extensions.profile_role AS ENUM ('client', 'director', 'member');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE extensions.project_role AS ENUM ('owner', 'director', 'member');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE extensions.ticket_type AS ENUM ('report', 'request');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- NOTE: 'blocked' deliberately absent — added by 20260528052326.
DO $$ BEGIN
  CREATE TYPE extensions.task_status AS ENUM
    ('not_started', 'in_progress', 'pending_approval', 'completed');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE extensions.task_priority AS ENUM
    ('extreme', 'high', 'medium', 'low', 'stretch');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE extensions.team_name AS ENUM
    ('technology', 'architecture', 'public_relations', 'engineering',
     'finance', 'research', 'legal', 'executive');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Legacy ticket status enum (quoted name, used by tickets.status default).
DO $$ BEGIN
  CREATE TYPE extensions."status enum" AS ENUM ('pending', 'denied', 'in-progress', 'done');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- NOTE: Helper/trigger functions are defined in section 9b, AFTER all tables
-- exist. SQL-language functions (e.g. user_profile_id, is_project_member) have
-- their bodies parsed and validated at CREATE time, so they must come after the
-- tables they reference. plpgsql trigger functions could come earlier, but are
-- grouped with the rest for clarity.

-- ---------------------------------------------------------------------
-- 3. Core identity tables (no dependency on projects)
-- ---------------------------------------------------------------------
CREATE TABLE public.profiles (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid         uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  name        text NOT NULL,
  email       text,
  role        extensions.profile_role NOT NULL,
  config      jsonb DEFAULT '{}'::jsonb,
  department  text,
  eid         text,
  graduation  smallint,
  discord_id  bigint,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_profiles_email ON public.profiles (email);
CREATE INDEX idx_profiles_role  ON public.profiles (role);
CREATE INDEX idx_profiles_uid   ON public.profiles (uid);

CREATE TABLE public.projects (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  url_slug     text NOT NULL UNIQUE,
  company_name text NOT NULL,
  config       jsonb DEFAULT '{}'::jsonb,
  created_by   bigint REFERENCES public.profiles(id),
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_projects_created_by ON public.projects (created_by);
CREATE INDEX idx_projects_url_slug   ON public.projects (url_slug);

CREATE TABLE public.project_members (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id  bigint NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  profile_id  bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  role        extensions.project_role NOT NULL,
  assigned_by bigint REFERENCES public.profiles(id),
  created_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT project_members_project_id_profile_id_key UNIQUE (project_id, profile_id)
);
CREATE INDEX idx_project_members_profile         ON public.project_members (profile_id);
CREATE INDEX idx_project_members_profile_project ON public.project_members (profile_id, project_id);
CREATE INDEX idx_project_members_project         ON public.project_members (project_id);
CREATE INDEX idx_project_members_role            ON public.project_members (role);

-- ---------------------------------------------------------------------
-- 4. Messaging
-- ---------------------------------------------------------------------
CREATE TABLE public.conversations (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at         timestamptz NOT NULL DEFAULT now(),
  client_profile_id  bigint REFERENCES public.profiles(id),
  director_profile_id bigint REFERENCES public.profiles(id),
  project_id         bigint REFERENCES public.projects(id)
);
CREATE INDEX idx_conversations_client_profile   ON public.conversations (client_profile_id);
CREATE INDEX idx_conversations_director_profile ON public.conversations (director_profile_id);
CREATE INDEX idx_conversations_project          ON public.conversations (project_id);

CREATE TABLE public.messages (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at        timestamptz NOT NULL DEFAULT now(),
  sender_uid        uuid DEFAULT auth.uid() REFERENCES auth.users(id),
  sender_role       text NOT NULL,
  content           text DEFAULT ''::text,
  conversation_id   bigint REFERENCES public.conversations(id),
  sender_profile_id bigint REFERENCES public.profiles(id),
  edited_at         timestamptz,
  reply_to_id       bigint REFERENCES public.messages(id) ON DELETE SET NULL,
  is_pinned         boolean NOT NULL DEFAULT false,
  pinned_at         timestamptz
);
CREATE INDEX idx_messages_sender_profile ON public.messages (sender_profile_id);
CREATE INDEX messages_pinned_idx         ON public.messages (conversation_id, pinned_at DESC) WHERE (is_pinned = true);
CREATE INDEX messages_reply_to_id_idx    ON public.messages (reply_to_id) WHERE (reply_to_id IS NOT NULL);
COMMENT ON COLUMN public.messages.edited_at   IS 'Timestamp of the latest content edit; null if never edited. Set by the client on PATCH.';
COMMENT ON COLUMN public.messages.reply_to_id IS 'If set, this message is a reply quoting the referenced message. On delete of the parent, this becomes NULL (the quote keeps showing "[deleted]" rather than orphaning the row).';
COMMENT ON COLUMN public.messages.is_pinned   IS 'Whether this message is pinned at the top of its conversation.';
COMMENT ON COLUMN public.messages.pinned_at   IS 'Timestamp when the message was pinned; sorts the pinned strip newest-first.';

CREATE TABLE public.message_attachments (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id bigint NOT NULL REFERENCES public.messages(id) ON DELETE CASCADE,
  path       text NOT NULL,
  name       text NOT NULL,
  mime_type  text,
  meta       jsonb,
  sort_index integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX message_attachments_message_id_idx ON public.message_attachments (message_id, sort_index);
COMMENT ON TABLE public.message_attachments IS 'Per-message attachments. Many-to-one with messages. sort_index controls render order in the bubble grid (0-based).';

CREATE TABLE public.message_unfurls (
  message_id  bigint PRIMARY KEY REFERENCES public.messages(id) ON DELETE CASCADE,
  url         text NOT NULL,
  title       text,
  description text,
  image_url   text,
  site_name   text,
  fetched_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX message_unfurls_url_idx ON public.message_unfurls (url);
COMMENT ON TABLE public.message_unfurls IS 'OpenGraph previews fetched server-side for the first URL in a message. One row per message at most.';

CREATE TABLE public.conversation_reads (
  conversation_id bigint NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
  profile_id      bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  last_read_at    timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (conversation_id, profile_id)
);
CREATE INDEX conversation_reads_profile_idx ON public.conversation_reads (profile_id);

-- ---------------------------------------------------------------------
-- 5. Tickets
-- ---------------------------------------------------------------------
CREATE TABLE public.tickets (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid         uuid DEFAULT auth.uid(),
  ticket_type extensions.ticket_type NOT NULL,
  title       text,
  subject     text NOT NULL,
  message     text NOT NULL,
  name        text,
  email       text,
  department  text,
  director    text,
  assign_to   text,
  project     text,
  status      extensions."status enum" DEFAULT 'pending'::extensions."status enum",
  customer_id text,
  numid       text,
  attachments jsonb,
  project_id  bigint REFERENCES public.projects(id),
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_tickets_project_id ON public.tickets (project_id);
CREATE INDEX idx_tickets_status     ON public.tickets (status);
CREATE INDEX idx_tickets_type       ON public.tickets (ticket_type);
CREATE INDEX idx_tickets_uid        ON public.tickets (uid);

-- ---------------------------------------------------------------------
-- 6. Lifecycle (project roadmap)
-- ---------------------------------------------------------------------
CREATE TABLE public.lifecycle_projects (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL REFERENCES public.projects(id),
  title      text NOT NULL,
  completed  boolean NOT NULL DEFAULT false,
  image      text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_lifecycle_projects_project ON public.lifecycle_projects (project_id);

CREATE TABLE public.lifecycle_tasks (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lifecycle_project_id bigint NOT NULL REFERENCES public.lifecycle_projects(id) ON DELETE CASCADE,
  title               text NOT NULL,
  description         text,
  status              extensions.task_status NOT NULL DEFAULT 'not_started'::extensions.task_status,
  team                extensions.team_name NOT NULL,
  due_date            date NOT NULL,
  tentative           boolean NOT NULL DEFAULT false,
  assigned_by         bigint REFERENCES public.profiles(id),
  priority            extensions.task_priority NOT NULL DEFAULT 'medium'::extensions.task_priority,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_lifecycle_tasks_project ON public.lifecycle_tasks (lifecycle_project_id);
CREATE INDEX idx_lifecycle_tasks_status  ON public.lifecycle_tasks (status);

CREATE TABLE public.lifecycle_task_assignees (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id    bigint NOT NULL REFERENCES public.lifecycle_tasks(id) ON DELETE CASCADE,
  profile_id bigint NOT NULL REFERENCES public.profiles(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT lifecycle_task_assignees_task_id_profile_id_key UNIQUE (task_id, profile_id)
);
CREATE INDEX idx_lifecycle_task_assignees_profile ON public.lifecycle_task_assignees (profile_id);

-- ---------------------------------------------------------------------
-- 7. Custom forms
-- ---------------------------------------------------------------------
CREATE TABLE public.custom_form_schemas (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       text NOT NULL,
  description text,
  fields      jsonb NOT NULL DEFAULT '[]'::jsonb,
  assigned_to text[] DEFAULT '{}'::text[],
  is_active   boolean DEFAULT true,
  created_by  uuid DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz DEFAULT now()
);

CREATE TABLE public.custom_form_submissions (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  form_id    bigint NOT NULL REFERENCES public.custom_form_schemas(id) ON DELETE CASCADE,
  user_id    uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  data       jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  project_id bigint REFERENCES public.projects(id),
  CONSTRAINT unique_form_submission UNIQUE (form_id, user_id, project_id)
);
CREATE INDEX idx_custom_form_submissions_data ON public.custom_form_submissions USING gin (data);

-- ---------------------------------------------------------------------
-- 8. Client AI / RAG / files / questionnaire
-- ---------------------------------------------------------------------
CREATE TABLE public.legal_documents (
  id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content   text,
  metadata  jsonb,
  embedding public.vector
);

CREATE TABLE public.client_knowledge (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  uid        uuid NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id),
  content    text NOT NULL,
  metadata   jsonb DEFAULT '{}'::jsonb,
  embedding  public.vector
);
COMMENT ON TABLE public.client_knowledge IS 'Client RAG Knowledge Base';

CREATE TABLE public.client_files (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at   timestamptz NOT NULL DEFAULT now(),
  file_name    text NOT NULL,
  storage_path text NOT NULL,
  metadata     jsonb,
  uid          uuid DEFAULT auth.uid() REFERENCES auth.users(id),
  file_type    text DEFAULT 'pdf'::text,
  file_size    bigint
);
CREATE INDEX idx_client_files_uid ON public.client_files (uid);
COMMENT ON TABLE public.client_files IS 'All file types clients save';

CREATE TABLE public.client_chat_sessions (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  uid        uuid DEFAULT auth.uid() REFERENCES auth.users(id),
  title      text,
  metadata   jsonb,
  project_id bigint REFERENCES public.projects(id) ON DELETE SET NULL
);
COMMENT ON TABLE public.client_chat_sessions IS 'Store previous chat sessions for client';

CREATE TABLE public.client_chat_messages (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id       bigint NOT NULL REFERENCES public.client_chat_sessions(id) ON DELETE CASCADE,
  role             text NOT NULL CHECK (role = ANY (ARRAY['user'::text, 'assistant'::text, 'system'::text])),
  content          text NOT NULL,
  sources          jsonb,
  attachments      jsonb,
  model_preference text,
  is_cancelled     boolean NOT NULL DEFAULT false,
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX client_chat_messages_session_idx     ON public.client_chat_messages (session_id, created_at);
CREATE INDEX client_chat_sessions_uid_updated_idx ON public.client_chat_sessions (uid, updated_at DESC);

CREATE TABLE public.questionnaire_responses (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uid             uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  responses       jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  submitted_forms text[] NOT NULL DEFAULT '{}'::text[]
);
COMMENT ON TABLE public.questionnaire_responses IS 'store clients'' responses';

-- ---------------------------------------------------------------------
-- 9. Public website intake
-- ---------------------------------------------------------------------
CREATE TABLE public.website_forms (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  name       text,
  email      text,
  subject    text,
  message    text,
  ip_address text
);

-- ---------------------------------------------------------------------
-- 9b. Helper functions (SECURITY DEFINER, search_path hardened)
--     Defined AFTER tables because SQL-language function bodies are validated
--     at CREATE time. set_updated_at() and is_project_director() are
--     intentionally NOT here (finance migration owns them via CREATE OR REPLACE).
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_updated_at()
  RETURNS trigger
  LANGUAGE plpgsql
  SET search_path TO 'pg_catalog', 'pg_temp'
AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END; $$;

CREATE OR REPLACE FUNCTION public.user_profile_id(check_uid uuid)
  RETURNS bigint
  LANGUAGE sql
  STABLE SECURITY DEFINER
  SET search_path TO 'pg_catalog', 'pg_temp'
AS $$
  SELECT id FROM public.profiles WHERE uid = auth.uid() LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.current_user_role()
  RETURNS text
  LANGUAGE sql
  STABLE SECURITY DEFINER
  SET search_path TO 'pg_catalog', 'pg_temp'
AS $$
  SELECT role FROM public.profiles WHERE uid = auth.uid();
$$;

CREATE OR REPLACE FUNCTION public.is_director(check_uid uuid)
  RETURNS boolean
  LANGUAGE sql
  STABLE SECURITY DEFINER
  SET search_path TO 'pg_catalog', 'pg_temp'
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE uid = auth.uid() AND role = 'director'
  );
$$;

CREATE OR REPLACE FUNCTION public.is_project_member(_project_id bigint)
  RETURNS boolean
  LANGUAGE sql
  STABLE SECURITY DEFINER
  SET search_path TO 'pg_catalog', 'pg_temp'
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.project_members pm
    JOIN public.profiles p ON p.id = pm.profile_id
    WHERE pm.project_id = _project_id
      AND p.uid = auth.uid()
  );
$$;

CREATE OR REPLACE FUNCTION private.user_project_ids()
  RETURNS SETOF bigint
  LANGUAGE sql
  STABLE SECURITY DEFINER
  SET search_path TO 'pg_catalog', 'pg_temp'
AS $$
  SELECT pm.project_id
  FROM public.project_members pm
  WHERE pm.profile_id = public.user_profile_id(auth.uid());
$$;

-- Trigger functions for auto-linking directors to projects.
CREATE OR REPLACE FUNCTION public.auto_link_director_to_projects()
  RETURNS trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'pg_catalog', 'pg_temp'
AS $$
BEGIN
  IF NEW.role = 'director' THEN
    INSERT INTO public.project_members (project_id, profile_id, role)
    SELECT p.id, NEW.id, 'director'
    FROM public.projects p
    ON CONFLICT DO NOTHING;
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.auto_link_directors_to_new_project()
  RETURNS trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'pg_catalog', 'pg_temp'
AS $$
BEGIN
  INSERT INTO public.project_members (project_id, profile_id, role)
  SELECT NEW.id, p.id, 'director'
  FROM public.profiles p
  WHERE p.role = 'director'
  ON CONFLICT DO NOTHING;

  IF NEW.created_by IS NOT NULL THEN
    INSERT INTO public.project_members (project_id, profile_id, role)
    VALUES (NEW.id, NEW.created_by, 'owner')
    ON CONFLICT DO NOTHING;
  END IF;

  RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------
-- 10. RPCs that depend on the tables above
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.mark_conversation_read(p_conversation_id bigint)
  RETURNS void
  LANGUAGE sql
AS $$
  INSERT INTO public.conversation_reads (conversation_id, profile_id, last_read_at)
  VALUES (p_conversation_id, public.user_profile_id(auth.uid()), now())
  ON CONFLICT (conversation_id, profile_id)
  DO UPDATE SET last_read_at = now();
$$;

CREATE OR REPLACE FUNCTION public.match_client_knowledge(
  _query_embedding public.vector,
  _match_count integer DEFAULT 5,
  _filter_uid uuid DEFAULT NULL::uuid,
  _similarity_threshold double precision DEFAULT 0.5
)
  RETURNS TABLE(id bigint, content text, metadata jsonb, similarity double precision)
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public'
AS $$
BEGIN
  RETURN QUERY
  SELECT ck.id, ck.content, ck.metadata,
    1 - (ck.embedding <=> _query_embedding) AS similarity
  FROM client_knowledge ck
  WHERE (_filter_uid IS NULL OR ck.uid = _filter_uid)
    AND 1 - (ck.embedding <=> _query_embedding) > _similarity_threshold
  ORDER BY ck.embedding <=> _query_embedding
  LIMIT _match_count;
END;
$$;

-- ---------------------------------------------------------------------
-- 11. Triggers
-- ---------------------------------------------------------------------
CREATE TRIGGER set_profiles_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
CREATE TRIGGER trg_auto_link_director_to_projects
  AFTER INSERT ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.auto_link_director_to_projects();

CREATE TRIGGER set_projects_updated_at
  BEFORE UPDATE ON public.projects
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();
CREATE TRIGGER trg_auto_link_directors_to_new_project
  AFTER INSERT ON public.projects
  FOR EACH ROW EXECUTE FUNCTION public.auto_link_directors_to_new_project();

CREATE TRIGGER set_tickets_updated_at
  BEFORE UPDATE ON public.tickets
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_lifecycle_projects_updated_at
  BEFORE UPDATE ON public.lifecycle_projects
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_lifecycle_tasks_updated_at
  BEFORE UPDATE ON public.lifecycle_tasks
  FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- ---------------------------------------------------------------------
-- 12. Row Level Security
-- ---------------------------------------------------------------------
ALTER TABLE public.profiles                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_members         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_attachments     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_unfurls         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_reads      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tickets                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lifecycle_projects      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lifecycle_tasks         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lifecycle_task_assignees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.custom_form_schemas     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.custom_form_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.legal_documents         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_knowledge        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_files            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_chat_sessions    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_chat_messages    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.questionnaire_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.website_forms           ENABLE ROW LEVEL SECURITY;

-- profiles
CREATE POLICY "Users can view own profile" ON public.profiles
  FOR SELECT USING (auth.uid() = uid);
CREATE POLICY "Directors can view all profiles" ON public.profiles
  FOR SELECT USING (public.is_director(auth.uid()));
CREATE POLICY "Users can update own profile" ON public.profiles
  FOR UPDATE USING (auth.uid() = uid) WITH CHECK (auth.uid() = uid);

-- projects
CREATE POLICY "Users can view their projects" ON public.projects
  FOR SELECT USING (id IN (SELECT private.user_project_ids()));

-- project_members
CREATE POLICY "Users can view project memberships" ON public.project_members
  FOR SELECT USING (project_id IN (SELECT private.user_project_ids()));
CREATE POLICY "Directors can assign members to projects" ON public.project_members
  FOR INSERT WITH CHECK (public.is_director(auth.uid()));
CREATE POLICY "Directors can remove members from projects" ON public.project_members
  FOR DELETE USING (public.is_director(auth.uid()));

-- conversations
CREATE POLICY "Users can view their own conversations" ON public.conversations
  FOR SELECT TO authenticated USING (
    (client_profile_id = public.user_profile_id(auth.uid()))
    OR (director_profile_id = public.user_profile_id(auth.uid()))
  );
CREATE POLICY "Users can create their own conversations" ON public.conversations
  FOR INSERT TO authenticated WITH CHECK (
    (client_profile_id = public.user_profile_id(auth.uid()))
    OR (director_profile_id = public.user_profile_id(auth.uid()))
  );

-- messages
CREATE POLICY "Users can view messages in their conversations" ON public.messages
  FOR SELECT TO authenticated USING (
    EXISTS (SELECT 1 FROM public.conversations conv
            WHERE conv.id = messages.conversation_id
              AND ((conv.client_profile_id = public.user_profile_id(auth.uid()))
                OR (conv.director_profile_id = public.user_profile_id(auth.uid()))))
  );
CREATE POLICY "Users can send messages in their conversations" ON public.messages
  FOR INSERT TO authenticated WITH CHECK (
    (sender_uid = auth.uid())
    AND EXISTS (SELECT 1 FROM public.conversations conv
                WHERE conv.id = messages.conversation_id
                  AND ((conv.client_profile_id = public.user_profile_id(auth.uid()))
                    OR (conv.director_profile_id = public.user_profile_id(auth.uid()))))
  );
CREATE POLICY "Allow users to update their own messages" ON public.messages
  FOR UPDATE TO authenticated USING (sender_uid = auth.uid()) WITH CHECK (sender_uid = auth.uid());

-- message_attachments
CREATE POLICY "see attachments of viewable messages" ON public.message_attachments
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.messages m
            JOIN public.conversations c ON c.id = m.conversation_id
            WHERE m.id = message_attachments.message_id
              AND ((c.client_profile_id = public.user_profile_id(auth.uid()))
                OR (c.director_profile_id = public.user_profile_id(auth.uid()))))
  );
CREATE POLICY "insert attachments to messages you sent" ON public.message_attachments
  FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.messages m
            WHERE m.id = message_attachments.message_id AND m.sender_uid = auth.uid())
  );
CREATE POLICY "delete attachments of messages you sent" ON public.message_attachments
  FOR DELETE USING (
    EXISTS (SELECT 1 FROM public.messages m
            WHERE m.id = message_attachments.message_id AND m.sender_uid = auth.uid())
  );

-- message_unfurls
CREATE POLICY "see unfurls for viewable messages" ON public.message_unfurls
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.messages m
            JOIN public.conversations c ON c.id = m.conversation_id
            WHERE m.id = message_unfurls.message_id
              AND ((c.client_profile_id = public.user_profile_id(auth.uid()))
                OR (c.director_profile_id = public.user_profile_id(auth.uid()))))
  );

-- conversation_reads
CREATE POLICY "own reads select" ON public.conversation_reads
  FOR SELECT USING (profile_id = public.user_profile_id(auth.uid()));
CREATE POLICY "own reads insert" ON public.conversation_reads
  FOR INSERT WITH CHECK (profile_id = public.user_profile_id(auth.uid()));
CREATE POLICY "own reads update" ON public.conversation_reads
  FOR UPDATE USING (profile_id = public.user_profile_id(auth.uid()))
              WITH CHECK (profile_id = public.user_profile_id(auth.uid()));

-- tickets
CREATE POLICY "Project members can view tickets" ON public.tickets
  FOR SELECT USING (
    public.is_director(auth.uid())
    OR ((project_id IS NOT NULL) AND public.is_project_member(project_id))
  );
CREATE POLICY "Clients can insert requests" ON public.tickets
  FOR INSERT WITH CHECK (
    (ticket_type = 'request'::extensions.ticket_type)
    AND (public.current_user_role() = 'client'::text)
    AND ((project_id IS NULL) OR public.is_project_member(project_id))
  );
CREATE POLICY "Members and directors can insert reports" ON public.tickets
  FOR INSERT WITH CHECK (
    (ticket_type = 'report'::extensions.ticket_type)
    AND (public.current_user_role() = ANY (ARRAY['director'::text, 'member'::text]))
    AND ((project_id IS NULL) OR public.is_project_member(project_id))
  );
CREATE POLICY "Project members can update tickets" ON public.tickets
  FOR UPDATE USING (
    (auth.uid() = uid) OR public.is_director(auth.uid())
    OR ((project_id IS NOT NULL) AND EXISTS (
      SELECT 1 FROM public.project_members pm
      JOIN public.profiles p ON p.id = pm.profile_id
      WHERE pm.project_id = tickets.project_id AND p.uid = auth.uid()))
  ) WITH CHECK (
    (auth.uid() = uid) OR public.is_director(auth.uid())
    OR ((project_id IS NOT NULL) AND EXISTS (
      SELECT 1 FROM public.project_members pm
      JOIN public.profiles p ON p.id = pm.profile_id
      WHERE pm.project_id = tickets.project_id AND p.uid = auth.uid()))
  );

-- lifecycle_projects
CREATE POLICY "Users can view lifecycle projects" ON public.lifecycle_projects
  FOR SELECT USING (project_id IN (SELECT private.user_project_ids()));
CREATE POLICY "Directors can manage lifecycle projects" ON public.lifecycle_projects
  FOR ALL TO authenticated USING (public.is_director(auth.uid())) WITH CHECK (public.is_director(auth.uid()));

-- lifecycle_tasks
CREATE POLICY "Users can view lifecycle tasks" ON public.lifecycle_tasks
  FOR SELECT USING (
    lifecycle_project_id IN (
      SELECT lifecycle_projects.id FROM public.lifecycle_projects
      WHERE lifecycle_projects.project_id IN (SELECT private.user_project_ids()))
  );
CREATE POLICY "Directors can manage lifecycle tasks" ON public.lifecycle_tasks
  FOR ALL TO authenticated USING (public.is_director(auth.uid())) WITH CHECK (public.is_director(auth.uid()));

-- lifecycle_task_assignees
CREATE POLICY "Users can view task assignees" ON public.lifecycle_task_assignees
  FOR SELECT USING (
    task_id IN (
      SELECT lt.id FROM public.lifecycle_tasks lt
      JOIN public.lifecycle_projects lp ON lp.id = lt.lifecycle_project_id
      WHERE lp.project_id IN (SELECT private.user_project_ids()))
  );
CREATE POLICY "Directors can manage task assignees" ON public.lifecycle_task_assignees
  FOR ALL TO authenticated USING (public.is_director(auth.uid())) WITH CHECK (public.is_director(auth.uid()));

-- custom_form_schemas
CREATE POLICY custom_form_schemas_select_authenticated ON public.custom_form_schemas
  FOR SELECT TO authenticated USING (true);
CREATE POLICY custom_form_schemas_insert_own_row ON public.custom_form_schemas
  FOR INSERT TO authenticated WITH CHECK (created_by = auth.uid());
CREATE POLICY custom_form_schemas_update_own_row ON public.custom_form_schemas
  FOR UPDATE TO authenticated USING (created_by = auth.uid()) WITH CHECK (created_by = auth.uid());
CREATE POLICY custom_form_schemas_delete_own_row ON public.custom_form_schemas
  FOR DELETE TO authenticated USING (created_by = auth.uid());

-- custom_form_submissions
CREATE POLICY "Users can view relevant submissions" ON public.custom_form_submissions
  FOR SELECT USING (
    (auth.uid() = user_id)
    OR EXISTS (SELECT 1 FROM public.custom_form_schemas s
               WHERE s.id = custom_form_submissions.form_id
                 AND ((s.created_by = auth.uid())
                   OR (custom_form_submissions.project_id IN (SELECT private.user_project_ids()))))
  );
CREATE POLICY "Users can insert own submissions" ON public.custom_form_submissions
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Only submitter can update" ON public.custom_form_submissions
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Authorized deletion" ON public.custom_form_submissions
  FOR DELETE USING (
    (auth.uid() = user_id)
    OR EXISTS (SELECT 1 FROM public.custom_form_schemas s
               WHERE s.id = custom_form_submissions.form_id AND s.created_by = auth.uid())
  );

-- legal_documents
CREATE POLICY "Authenticated users can view legal documents" ON public.legal_documents
  FOR SELECT TO authenticated USING (auth.role() = 'authenticated'::text);

-- client_knowledge (two overlapping sets present in live DB; reproduced as-is)
CREATE POLICY "Users can view their own knowledge" ON public.client_knowledge
  FOR SELECT USING (auth.uid() = uid);
CREATE POLICY "Users can insert their own knowledge" ON public.client_knowledge
  FOR INSERT WITH CHECK (auth.uid() = uid);
CREATE POLICY "Users can delete their own knowledge" ON public.client_knowledge
  FOR DELETE USING (auth.uid() = uid);
CREATE POLICY "Users can view own documents" ON public.client_knowledge
  FOR SELECT TO authenticated USING (auth.uid() = uid);
CREATE POLICY "Users can insert own documents" ON public.client_knowledge
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = uid);
CREATE POLICY "Users can update own documents" ON public.client_knowledge
  FOR UPDATE TO authenticated USING (auth.uid() = uid) WITH CHECK (auth.uid() = uid);
CREATE POLICY "Users can delete documents" ON public.client_knowledge
  FOR DELETE TO authenticated USING (auth.uid() = uid);

-- client_files
CREATE POLICY "Users can view their own files" ON public.client_files
  FOR SELECT USING (auth.uid() = uid);
CREATE POLICY "Users can insert their own files" ON public.client_files
  FOR INSERT WITH CHECK (auth.uid() = uid);
CREATE POLICY "Users can delete their own files" ON public.client_files
  FOR DELETE USING (auth.uid() = uid);

-- client_chat_sessions
CREATE POLICY "Users can view own chat sessions" ON public.client_chat_sessions
  FOR SELECT TO authenticated USING (auth.uid() = uid);
CREATE POLICY "Users can insert own chat sessions" ON public.client_chat_sessions
  FOR INSERT TO authenticated WITH CHECK (auth.uid() = uid);
CREATE POLICY "Users can update own chat sessions" ON public.client_chat_sessions
  FOR UPDATE TO authenticated USING (auth.uid() = uid) WITH CHECK (auth.uid() = uid);
CREATE POLICY "Users can delete own chat sessions" ON public.client_chat_sessions
  FOR DELETE TO authenticated USING (auth.uid() = uid);

-- client_chat_messages
CREATE POLICY "Users can view messages in own sessions" ON public.client_chat_messages
  FOR SELECT TO authenticated USING (
    EXISTS (SELECT 1 FROM public.client_chat_sessions s
            WHERE s.id = client_chat_messages.session_id AND s.uid = auth.uid())
  );
CREATE POLICY "Users can insert messages in own sessions" ON public.client_chat_messages
  FOR INSERT TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM public.client_chat_sessions s
            WHERE s.id = client_chat_messages.session_id AND s.uid = auth.uid())
  );
CREATE POLICY "Users can update messages in own sessions" ON public.client_chat_messages
  FOR UPDATE TO authenticated USING (
    EXISTS (SELECT 1 FROM public.client_chat_sessions s
            WHERE s.id = client_chat_messages.session_id AND s.uid = auth.uid())
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM public.client_chat_sessions s
            WHERE s.id = client_chat_messages.session_id AND s.uid = auth.uid())
  );
CREATE POLICY "Users can delete messages in own sessions" ON public.client_chat_messages
  FOR DELETE TO authenticated USING (
    EXISTS (SELECT 1 FROM public.client_chat_sessions s
            WHERE s.id = client_chat_messages.session_id AND s.uid = auth.uid())
  );

-- questionnaire_responses
CREATE POLICY "users can read responses" ON public.questionnaire_responses
  FOR SELECT USING (auth.uid() = uid);
CREATE POLICY "users can create responses" ON public.questionnaire_responses
  FOR INSERT WITH CHECK (auth.uid() = uid);
CREATE POLICY "users can update responses" ON public.questionnaire_responses
  FOR UPDATE USING (auth.uid() = uid) WITH CHECK (auth.uid() = uid);

-- website_forms
CREATE POLICY "Anyone can submit website forms" ON public.website_forms
  FOR INSERT WITH CHECK (true);
CREATE POLICY "Authenticated users can view website forms" ON public.website_forms
  FOR SELECT TO authenticated USING (auth.role() = 'authenticated'::text);

-- ---------------------------------------------------------------------
-- 13. Realtime publication
-- ---------------------------------------------------------------------
DO $$ BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.message_attachments;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.message_unfurls;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ---------------------------------------------------------------------
-- 14. Storage buckets
-- ---------------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES
  ('Files', 'Files', false, NULL, NULL),
  ('Message Attachments', 'Message Attachments', false, 10485760,
     ARRAY['image/jpeg','image/png','application/pdf']),
  ('questionnaire-attachments', 'questionnaire-attachments', false, 26214400,
     ARRAY['image/jpeg','image/png','image/webp','image/gif','image/svg+xml',
           'application/pdf','application/msword',
           'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
           'application/vnd.ms-excel',
           'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
           'application/vnd.ms-powerpoint',
           'application/vnd.openxmlformats-officedocument.presentationml.presentation',
           'application/dxf','image/vnd.dwg']),
  ('ticket-attachments', 'ticket-attachments', false, NULL, NULL)
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------------
-- 15. Storage object policies
--     (Note: live DB also has orphaned 'request-attachments' policies for a
--      bucket that does not exist; intentionally omitted.)
-- ---------------------------------------------------------------------
-- Files bucket
CREATE POLICY "Allow users to access and upload to buckets 14exqv_0" ON storage.objects
  FOR SELECT TO anon, authenticated USING (bucket_id = 'Files'::text);
CREATE POLICY "Directors can upload Files" ON storage.objects
  FOR INSERT TO authenticated WITH CHECK ((bucket_id = 'Files'::text) AND public.is_director(auth.uid()));
CREATE POLICY "Directors can update Files" ON storage.objects
  FOR UPDATE TO authenticated USING ((bucket_id = 'Files'::text) AND public.is_director(auth.uid()))
  WITH CHECK ((bucket_id = 'Files'::text) AND public.is_director(auth.uid()));
CREATE POLICY "Directors can delete Files" ON storage.objects
  FOR DELETE TO authenticated USING ((bucket_id = 'Files'::text) AND public.is_director(auth.uid()));

-- Message Attachments bucket
CREATE POLICY "Allow message attachments cu7rh3_0" ON storage.objects
  FOR INSERT TO authenticated WITH CHECK (bucket_id = 'Message Attachments'::text);
CREATE POLICY "Allow users to read from message attachments cu7rh3_0" ON storage.objects
  FOR SELECT TO authenticated USING (bucket_id = 'Message Attachments'::text);

-- ticket-attachments bucket
CREATE POLICY "Authenticated users can read ticket-attachments" ON storage.objects
  FOR SELECT USING ((bucket_id = 'ticket-attachments'::text) AND (auth.role() = 'authenticated'::text));
CREATE POLICY "Authenticated users can upload ticket-attachments" ON storage.objects
  FOR INSERT WITH CHECK ((bucket_id = 'ticket-attachments'::text) AND (auth.role() = 'authenticated'::text));

-- questionnaire-attachments bucket (owner-folder scoped)
CREATE POLICY "Users can view own files" ON storage.objects
  FOR SELECT TO authenticated USING (
    (bucket_id = 'questionnaire-attachments'::text)
    AND ((storage.foldername(name))[1] = (auth.uid())::text)
  );
CREATE POLICY "Users can upload own files" ON storage.objects
  FOR INSERT TO authenticated WITH CHECK (
    (bucket_id = 'questionnaire-attachments'::text)
    AND ((storage.foldername(name))[1] = (auth.uid())::text)
  );
CREATE POLICY "Users can delete own files" ON storage.objects
  FOR DELETE TO authenticated USING (
    (bucket_id = 'questionnaire-attachments'::text)
    AND ((storage.foldername(name))[1] = (auth.uid())::text)
  );
