-- ============================================================================
-- project_events + project_event_attendees
-- ----------------------------------------------------------------------------
-- Native calendar tables. The previous design proxied the director's personal
-- Google Calendar (per-project filtering by client email in attendees[]); this
-- migration replaces that with project-scoped rows + per-attendee RSVP. Both
-- directors and clients get full CRUD on their own project events, RSVP is a
-- single UPDATE on project_event_attendees, and the per-user .ics feed
-- (frontend/app/api/contact/calendar/feed/[token]/route.ts) replaces the need
-- for Google Calendar UI to surface events.
--
-- Idempotent and additive. Re-runs are safe; existing rows are not modified.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Tables
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.project_events (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id  bigint NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  title       text NOT NULL,
  description text,
  location    text,
  start_at    timestamptz NOT NULL,
  end_at      timestamptz NOT NULL,
  all_day     boolean NOT NULL DEFAULT false,
  created_by  bigint NOT NULL REFERENCES public.profiles(id),
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT project_events_title_nonempty CHECK (char_length(title) > 0),
  CONSTRAINT project_events_end_after_start CHECK (end_at > start_at)
);

CREATE INDEX IF NOT EXISTS idx_project_events_project_start
  ON public.project_events (project_id, start_at);

CREATE INDEX IF NOT EXISTS idx_project_events_created_by
  ON public.project_events (created_by);

CREATE TABLE IF NOT EXISTS public.project_event_attendees (
  event_id     bigint NOT NULL REFERENCES public.project_events(id) ON DELETE CASCADE,
  profile_id   bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  response     text NOT NULL DEFAULT 'needsAction'
                CHECK (response IN ('accepted', 'declined', 'tentative', 'needsAction')),
  responded_at timestamptz,
  PRIMARY KEY (event_id, profile_id)
);

CREATE INDEX IF NOT EXISTS idx_project_event_attendees_profile
  ON public.project_event_attendees (profile_id);

-- ----------------------------------------------------------------------------
-- 2. updated_at + responded_at triggers
-- ----------------------------------------------------------------------------
-- Reuses public.touch_updated_at() defined in 20260607000000_questionnaire_full_system.sql.
DROP TRIGGER IF EXISTS trg_touch_project_events_updated_at ON public.project_events;
CREATE TRIGGER trg_touch_project_events_updated_at
  BEFORE UPDATE ON public.project_events
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

CREATE OR REPLACE FUNCTION public.stamp_event_attendee_responded_at()
  RETURNS trigger
  LANGUAGE plpgsql
AS $$
BEGIN
  -- Stamp when the attendee moves off 'needsAction' (and clear it if they go back).
  IF NEW.response IS DISTINCT FROM OLD.response THEN
    IF NEW.response <> 'needsAction' THEN
      NEW.responded_at := now();
    ELSE
      NEW.responded_at := NULL;
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_stamp_event_attendee_responded_at ON public.project_event_attendees;
CREATE TRIGGER trg_stamp_event_attendee_responded_at
  BEFORE UPDATE ON public.project_event_attendees
  FOR EACH ROW EXECUTE FUNCTION public.stamp_event_attendee_responded_at();

-- ----------------------------------------------------------------------------
-- 3. RLS
-- ----------------------------------------------------------------------------
-- Helpers used below (defined in 20260101000000_baseline_schema.sql):
--   public.user_profile_id(auth.uid())   -- the caller's profiles.id
--   public.is_director(auth.uid())       -- the caller's role = 'director'
--   public.is_project_member(project_id) -- the caller is on this project
--   private.user_project_ids()           -- set of project ids the caller can see

ALTER TABLE public.project_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_event_attendees ENABLE ROW LEVEL SECURITY;

-- project_events ------------------------------------------------------------
DROP POLICY IF EXISTS project_events_select_members ON public.project_events;
CREATE POLICY project_events_select_members ON public.project_events
  FOR SELECT TO authenticated
  USING (project_id IN (SELECT private.user_project_ids()));

DROP POLICY IF EXISTS project_events_insert_members ON public.project_events;
CREATE POLICY project_events_insert_members ON public.project_events
  FOR INSERT TO authenticated
  WITH CHECK (
    project_id IN (SELECT private.user_project_ids())
    AND created_by = public.user_profile_id(auth.uid())
  );

-- The created_by = caller check on WITH CHECK prevents a member of project A
-- from inserting an event into project A while claiming it was created by
-- someone else (would otherwise look legit on SELECT since SELECT checks
-- project membership only). WITH CHECK re-runs against the post-image row.
DROP POLICY IF EXISTS project_events_update_creator_or_director ON public.project_events;
CREATE POLICY project_events_update_creator_or_director ON public.project_events
  FOR UPDATE TO authenticated
  USING (
    created_by = public.user_profile_id(auth.uid())
    OR public.is_director(auth.uid())
  )
  WITH CHECK (
    created_by = public.user_profile_id(auth.uid())
    OR public.is_director(auth.uid())
  );

DROP POLICY IF EXISTS project_events_delete_creator_or_director ON public.project_events;
CREATE POLICY project_events_delete_creator_or_director ON public.project_events
  FOR DELETE TO authenticated
  USING (
    created_by = public.user_profile_id(auth.uid())
    OR public.is_director(auth.uid())
  );

-- project_event_attendees ---------------------------------------------------
DROP POLICY IF EXISTS project_event_attendees_select_members ON public.project_event_attendees;
CREATE POLICY project_event_attendees_select_members ON public.project_event_attendees
  FOR SELECT TO authenticated
  USING (
    event_id IN (
      SELECT pe.id FROM public.project_events pe
      WHERE pe.project_id IN (SELECT private.user_project_ids())
    )
  );

-- Any project member can add attendees — but only to events on projects they
-- belong to. RLS does not let you invite someone from a project you're not on
-- because the inner SELECT only returns event ids the caller can see.
DROP POLICY IF EXISTS project_event_attendees_insert_members ON public.project_event_attendees;
CREATE POLICY project_event_attendees_insert_members ON public.project_event_attendees
  FOR INSERT TO authenticated
  WITH CHECK (
    event_id IN (
      SELECT pe.id FROM public.project_events pe
      WHERE pe.project_id IN (SELECT private.user_project_ids())
    )
  );

-- Self-service RSVP: the attendee can update their own row (so they can flip
-- accepted -> declined etc. without a director). Event creators and directors
-- can also update any attendee on their event/project.
DROP POLICY IF EXISTS project_event_attendees_update_self_creator_director
  ON public.project_event_attendees;
CREATE POLICY project_event_attendees_update_self_creator_director
  ON public.project_event_attendees
  FOR UPDATE TO authenticated
  USING (
    profile_id = public.user_profile_id(auth.uid())
    OR public.is_director(auth.uid())
    OR event_id IN (
      SELECT pe.id FROM public.project_events pe
      WHERE pe.created_by = public.user_profile_id(auth.uid())
    )
  )
  WITH CHECK (
    profile_id = public.user_profile_id(auth.uid())
    OR public.is_director(auth.uid())
    OR event_id IN (
      SELECT pe.id FROM public.project_events pe
      WHERE pe.created_by = public.user_profile_id(auth.uid())
    )
  );

DROP POLICY IF EXISTS project_event_attendees_delete_self_creator_director
  ON public.project_event_attendees;
CREATE POLICY project_event_attendees_delete_self_creator_director
  ON public.project_event_attendees
  FOR DELETE TO authenticated
  USING (
    profile_id = public.user_profile_id(auth.uid())
    OR public.is_director(auth.uid())
    OR event_id IN (
      SELECT pe.id FROM public.project_events pe
      WHERE pe.created_by = public.user_profile_id(auth.uid())
    )
  );
