-- Questionnaire schema hardening — close the gaps for a Google-Forms-grade
-- system on top of the EXISTING custom_form_schemas / custom_form_submissions
-- tables. Additive and idempotent: it adds columns/constraints/indexes only,
-- preserves every existing row, and invents no parallel tables.
--
-- PROPOSAL — defined in this worktree, ordered after the baseline. NOT applied
-- to the live database. Review before `supabase db push`.
--
-- Gaps addressed:
--   1. Submission lifecycle      — draft vs submitted status + submitted_at.
--   2. Schema versioning         — version counter on schemas + the version a
--                                  submission was answered against, so old
--                                  answers survive when a form's fields change.
--   3. Question ordering / shape — keep fields jsonb (flexible per-field types),
--                                  but pin the convention via a CHECK that it is
--                                  always a JSON array, and document the element
--                                  shape. Ordering = array index.
--   4. Assignment model          — assigned_to text[] is untyped ("all" sentinel
--                                  or uuid strings). We keep the column for back-
--                                  compat and add an OPTIONAL typed join table
--                                  for precise per-user / per-project assignment.
--   5. updated_at hygiene        — triggers so updated_at is trustworthy.

-- ---------------------------------------------------------------------------
-- 1. Submission lifecycle: draft vs submitted
-- ---------------------------------------------------------------------------
ALTER TABLE public.custom_form_submissions
  ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'submitted')),
  ADD COLUMN IF NOT EXISTS submitted_at timestamptz;

-- ---------------------------------------------------------------------------
-- 2. Schema versioning. Bump version whenever `fields` changes; submissions
--    record the version they were answered against so historical answers stay
--    interpretable after a form is edited.
-- ---------------------------------------------------------------------------
ALTER TABLE public.custom_form_schemas
  ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1;

ALTER TABLE public.custom_form_submissions
  ADD COLUMN IF NOT EXISTS schema_version integer NOT NULL DEFAULT 1;

CREATE OR REPLACE FUNCTION public.bump_form_schema_version()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.fields IS DISTINCT FROM OLD.fields THEN
    NEW.version := OLD.version + 1;
  END IF;
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_bump_form_schema_version ON public.custom_form_schemas;
CREATE TRIGGER trg_bump_form_schema_version
  BEFORE UPDATE ON public.custom_form_schemas
  FOR EACH ROW EXECUTE FUNCTION public.bump_form_schema_version();

-- ---------------------------------------------------------------------------
-- 3. Pin the fields-jsonb convention. fields must be a JSON array; each element
--    is { key:text, type:text, label:text, required:bool, options?:[], ... }.
--    Ordering is the array index. (Stays jsonb so per-field types/validation
--    evolve without a migration per field type — the right tradeoff for a
--    form-builder where the question set is user-defined and sparse.)
-- ---------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'custom_form_schemas_fields_is_array'
  ) THEN
    ALTER TABLE public.custom_form_schemas
      ADD CONSTRAINT custom_form_schemas_fields_is_array
      CHECK (jsonb_typeof(fields) = 'array');
  END IF;
END
$$;

-- ---------------------------------------------------------------------------
-- 4. Optional typed assignment join table. assigned_to text[] is retained for
--    back-compat (the live data uses the "all" sentinel). This table allows
--    precise targeting by user and/or project when a director wants it; absence
--    of any row + assigned_to = {all} means "everyone".
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.custom_form_assignments (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  form_id    bigint NOT NULL REFERENCES public.custom_form_schemas(id) ON DELETE CASCADE,
  user_id    uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  project_id bigint REFERENCES public.projects(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT custom_form_assignments_target_not_null
    CHECK (user_id IS NOT NULL OR project_id IS NOT NULL),
  CONSTRAINT custom_form_assignments_unique UNIQUE (form_id, user_id, project_id)
);
CREATE INDEX IF NOT EXISTS idx_custom_form_assignments_form
  ON public.custom_form_assignments (form_id);
CREATE INDEX IF NOT EXISTS idx_custom_form_assignments_user
  ON public.custom_form_assignments (user_id);

ALTER TABLE public.custom_form_assignments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS custom_form_assignments_select ON public.custom_form_assignments;
CREATE POLICY custom_form_assignments_select ON public.custom_form_assignments
  FOR SELECT TO authenticated USING (
    user_id = auth.uid()
    OR EXISTS (SELECT 1 FROM public.custom_form_schemas s
               WHERE s.id = custom_form_assignments.form_id AND s.created_by = auth.uid())
  );

DROP POLICY IF EXISTS custom_form_assignments_write ON public.custom_form_assignments;
CREATE POLICY custom_form_assignments_write ON public.custom_form_assignments
  FOR ALL TO authenticated USING (
    EXISTS (SELECT 1 FROM public.custom_form_schemas s
            WHERE s.id = custom_form_assignments.form_id AND s.created_by = auth.uid())
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM public.custom_form_schemas s
            WHERE s.id = custom_form_assignments.form_id AND s.created_by = auth.uid())
  );

-- ---------------------------------------------------------------------------
-- 5. updated_at hygiene on submissions.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_touch_submission_updated_at ON public.custom_form_submissions;
CREATE TRIGGER trg_touch_submission_updated_at
  BEFORE UPDATE ON public.custom_form_submissions
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
