-- Director-authored reusable form templates.
--
-- PROPOSAL — defined in this worktree, ordered after 20260612000000. NOT applied
-- to the live database. Review before `supabase db push`.
--
-- A template is a saved question set (no assignment/publishing/submissions). A
-- director can "save a form as a template" and start new forms from it. Kept in
-- its own table so templates never leak into the real forms list, RLS, or
-- submissions. Each director manages only their own templates.

CREATE TABLE IF NOT EXISTS public.custom_form_templates (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  description text,
  fields      jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_by  uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT custom_form_templates_fields_is_array
    CHECK (jsonb_typeof(fields) = 'array')
);

CREATE INDEX IF NOT EXISTS idx_custom_form_templates_creator
  ON public.custom_form_templates (created_by);

ALTER TABLE public.custom_form_templates ENABLE ROW LEVEL SECURITY;

-- A director sees and manages only their own templates.
DROP POLICY IF EXISTS custom_form_templates_all ON public.custom_form_templates;
CREATE POLICY custom_form_templates_all ON public.custom_form_templates
  FOR ALL TO authenticated
  USING (created_by = auth.uid())
  WITH CHECK (created_by = auth.uid());

COMMENT ON TABLE public.custom_form_templates IS
  'Director-authored reusable form templates (question sets). Not forms: no '
  'assignment, publishing, or submissions. RLS: owner-only.';
