-- Questionnaire full system — completes the Google-Forms-grade build on top of
-- the EXISTING custom_form_* tables and the 20260603000000 hardening migration.
--
-- PROPOSAL — defined in this worktree, ordered after the baseline + hardening.
-- NOT applied to the live database. Review before `supabase db push`.
--
-- This migration is additive and idempotent. It:
--   1. Re-asserts the hardening columns/constraints (so this file is safe to run
--      even if 20260603000000 has not been applied — no dependency on ordering).
--   2. Adds assignment-aware RLS so a client can read forms assigned to one of
--      their projects (the typed custom_form_assignments table replaces the
--      assigned_to='{all}' sentinel).
--   3. Tightens submission visibility so directors can read submissions for the
--      forms they own (already covered) and lets clients upsert drafts.
--   4. Deprecates questionnaire_responses (documented; data left intact).
--
-- Assumptions about pre-existing objects (from baseline 20260101000000):
--   - public.projects(id bigint PK)
--   - public.profiles(uid uuid, role text)  with role IN client/director/member
--   - private.user_project_ids() returns the caller's project ids
--   - public.is_director(check_uid uuid) returns boolean

-- ===========================================================================
-- 1. Re-assert hardening columns / constraints (idempotent, dependency-free).
-- ===========================================================================
ALTER TABLE public.custom_form_schemas
  ADD COLUMN IF NOT EXISTS version integer NOT NULL DEFAULT 1;

ALTER TABLE public.custom_form_submissions
  ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'submitted')),
  ADD COLUMN IF NOT EXISTS submitted_at timestamptz,
  ADD COLUMN IF NOT EXISTS schema_version integer NOT NULL DEFAULT 1;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'custom_form_schemas_fields_is_array'
  ) THEN
    ALTER TABLE public.custom_form_schemas
      ADD CONSTRAINT custom_form_schemas_fields_is_array
      CHECK (jsonb_typeof(fields) = 'array');
  END IF;
END
$$;

-- Bump version when fields change; keep updated_at trustworthy.
CREATE OR REPLACE FUNCTION public.bump_form_schema_version()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.fields IS DISTINCT FROM OLD.fields THEN
    NEW.version := OLD.version + 1;
  END IF;
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_bump_form_schema_version ON public.custom_form_schemas;
CREATE TRIGGER trg_bump_form_schema_version
  BEFORE UPDATE ON public.custom_form_schemas
  FOR EACH ROW EXECUTE FUNCTION public.bump_form_schema_version();

CREATE OR REPLACE FUNCTION public.touch_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_touch_submission_updated_at ON public.custom_form_submissions;
CREATE TRIGGER trg_touch_submission_updated_at
  BEFORE UPDATE ON public.custom_form_submissions
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

-- Stamp submitted_at automatically when status flips to 'submitted'.
CREATE OR REPLACE FUNCTION public.stamp_submission_submitted_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.status = 'submitted'
     AND (TG_OP = 'INSERT' OR OLD.status IS DISTINCT FROM 'submitted')
     AND NEW.submitted_at IS NULL THEN
    NEW.submitted_at := now();
  END IF;
  IF NEW.status = 'draft' THEN
    NEW.submitted_at := NULL;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_stamp_submission_submitted_at ON public.custom_form_submissions;
CREATE TRIGGER trg_stamp_submission_submitted_at
  BEFORE INSERT OR UPDATE ON public.custom_form_submissions
  FOR EACH ROW EXECUTE FUNCTION public.stamp_submission_submitted_at();

-- ===========================================================================
-- 2. Typed assignment table (replaces the assigned_to='{all}' sentinel).
--    Directors assign a form to a project; absence of any project row means the
--    form is not yet assigned. Re-asserted idempotently.
-- ===========================================================================
CREATE TABLE IF NOT EXISTS public.custom_form_assignments (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  form_id    bigint NOT NULL REFERENCES public.custom_form_schemas(id) ON DELETE CASCADE,
  user_id    uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  project_id bigint REFERENCES public.projects(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT custom_form_assignments_target_not_null
    CHECK (user_id IS NOT NULL OR project_id IS NOT NULL),
  CONSTRAINT custom_form_assignments_unique UNIQUE (form_id, user_id, project_id)
);
CREATE INDEX IF NOT EXISTS idx_custom_form_assignments_form
  ON public.custom_form_assignments (form_id);
CREATE INDEX IF NOT EXISTS idx_custom_form_assignments_user
  ON public.custom_form_assignments (user_id);
CREATE INDEX IF NOT EXISTS idx_custom_form_assignments_project
  ON public.custom_form_assignments (project_id);

ALTER TABLE public.custom_form_assignments ENABLE ROW LEVEL SECURITY;

-- SELECT: the assigned user, any member of the assigned project, or the form
-- owner (director). Uses private.user_project_ids() to scope project access.
DROP POLICY IF EXISTS custom_form_assignments_select ON public.custom_form_assignments;
CREATE POLICY custom_form_assignments_select ON public.custom_form_assignments
  FOR SELECT TO authenticated USING (
    user_id = auth.uid()
    OR project_id IN (SELECT private.user_project_ids())
    OR EXISTS (
      SELECT 1 FROM public.custom_form_schemas s
      WHERE s.id = custom_form_assignments.form_id AND s.created_by = auth.uid()
    )
  );

-- WRITE: only the form owner (director who created the schema) may assign.
DROP POLICY IF EXISTS custom_form_assignments_write ON public.custom_form_assignments;
CREATE POLICY custom_form_assignments_write ON public.custom_form_assignments
  FOR ALL TO authenticated USING (
    EXISTS (
      SELECT 1 FROM public.custom_form_schemas s
      WHERE s.id = custom_form_assignments.form_id AND s.created_by = auth.uid()
    )
  ) WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.custom_form_schemas s
      WHERE s.id = custom_form_assignments.form_id AND s.created_by = auth.uid()
    )
  );

-- ===========================================================================
-- 3. Assignment-aware read of schemas. The baseline already grants SELECT on
--    custom_form_schemas to every authenticated user (forms are not secret),
--    so clients can already read schema rows; the app filters to assigned forms
--    via custom_form_assignments. We add a covering index for that lookup and a
--    helper that the app/server actions rely on for "forms for this project".
-- ===========================================================================
CREATE INDEX IF NOT EXISTS idx_custom_form_submissions_form_user_project
  ON public.custom_form_submissions (form_id, user_id, project_id);

CREATE INDEX IF NOT EXISTS idx_custom_form_schemas_active
  ON public.custom_form_schemas (is_active);

-- ===========================================================================
-- 4. Deprecate questionnaire_responses. The live DB holds 1 legacy row keyed by
--    uid → form-id → field-name → answer. We DO NOT migrate it automatically
--    (its field keys do not map cleanly to the new typed schema ids); instead we
--    mark the table deprecated. New writes go to custom_form_submissions. The
--    legacy row is preserved and can be hand-migrated by a director if needed.
-- ===========================================================================
COMMENT ON TABLE public.questionnaire_responses IS
  'DEPRECATED 2026-06: superseded by custom_form_submissions (typed, versioned, '
  'draft/submitted). Retained read-only for the 1 historical row. Do not write.';

COMMENT ON COLUMN public.custom_form_submissions.status IS
  'draft = autosaved in progress; submitted = client confirmed (submitted_at set).';
COMMENT ON COLUMN public.custom_form_submissions.schema_version IS
  'custom_form_schemas.version this answer was captured against, so edits to a '
  'live form never reinterpret old answers.';
COMMENT ON TABLE public.custom_form_assignments IS
  'Typed form→project (or form→user) assignment. Replaces the assigned_to=''{all}'' '
  'sentinel on custom_form_schemas.';
